version: '2'
services:

    mongo_1:
        image: mongo
        container_name: mongo_1
        restart: always
        ports:
            - 27017:27017
        command: mongod --replSet test_replset

    mongo_2:
        image: mongo
        container_name: mongo_2
        restart: always
        ports:
            - 27018:27017
        command: mongod --replSet test_replset

    mongo_3:
        image: mongo
        container_name: mongo_3
        restart: always
        ports:
            - 27019:27017
        command: mongod --replSet test_replset
